[package]
name = "carlos"
version = "0.1.0"
edition = "2024"

[dependencies]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[build]
target = "x86_64-unknown-none"

[lib]
harness = false

[[bin]]
name = "kernel"
path = "src/main.rs"
harness = false