[package]
name = "carlos"
version = "0.1.0"
edition = "2024"

[dependencies]
x86 = "0.52.0"
linked_list_allocator = "0.10"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[lib]
crate-type = ["staticlib"]